### ISSUE TITLE
Test elk configuration on hoist changes

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#103]
Add more subnodes to our multinode testing so that the tests more closely resemble production. Currently we don't test the log host deployment in multinode testing because there is no subnode for the host.

**Comment by ConsoleCatzirl** [comment]
I have proposed BonnyCI/hoist#83 and BonnyCI/hoist#84 to add a log host to the multinode test.

**Comment by ConsoleCatzirl** [comment]
Once #99 is done, we will have another subnode to add to the multinode test.

**Comment by missaugustina** [comment]
What other parts are still remaining that need to be moved out to subnodes?

**Comment by ConsoleCatzirl** [comment]
The only part left to split out to make the multinode test match production is adding a multinode subnode for the zuul merger.

**Comment by missaugustina** [comment]
Looking for someone to set up the multinode subnode for the zuul merger! Note that once that is complete we may have additional tasks once this is deployed to the new cloud.

**Comment by ConsoleCatzirl** [comment]
We have elk tasks in our validation playbook, which runs in our test suite. Marking this done.
