### ISSUE TITLE
What exactly is BonnyCI?

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#116]
Summary of BonnyCI key features and how it differs from other CI as a Service options like TravisCI.

- [x] Review research to get some idea of existing CI user painpoints who are unhappy with current CI services
- [x] Freewrite/brainstorm with ideas of how to make the argument for BonnyCI based on ^^
- [x] Fill out missing prose
- [x] Initial Edit
- [x] Initial review submission
- [x] edit/review cycle until approved

**Comment by missaugustina** [comment]
https://github.com/BonnyCI/bonnyci.org/tree/issue116_whyBonnyCI

**Comment by missaugustina** [comment]
Currently scrawled out a brainstorm rough draft based on notes and initial research. Next step is to put together a logical outline/proof clearly stating the hypothesis and supporting arguments to ensure logical integrity and completeness.

**Comment by missaugustina** [comment]
Still working on outline - https://github.com/BonnyCI/bonnyci.org/commit/b49e5f7904dac2038cac4fc53a5e807854b488a2

**Comment by jasontclark** [comment]
Since this falls into the documentation realm, I've added myself to this issue.

**Comment by missaugustina** [comment]
I've been focusing on getting the Github events research wrapped up, so this has fallen by the wayside. I'm hoping to at least get the outline finished this week.

**Comment by jasontclark** [comment]
Created an etherpad to capture our drafts: https://etherpad.openstack.org/p/bonnyci_summary_drafts

**Comment by colettecello** [comment]
Hey there! Any updates on when we can expect this to move along/be done?

**Comment by jasontclark** [comment]
@colettecello I'm working on it this morning.  We should have a decent draft ready for review this afternoon.

**Comment by jasontclark** [comment]
Two draft summaries have been added to the etherpad: https://etherpad.openstack.org/p/bonnyci_summary_drafts

**Comment by mlangbehn** [comment]
@jasontclark: I replied on the etherpad. I like draft 2, but I think it needs to include "open source."

**Comment by jasontclark** [comment]
Final Copy (Long)
=============
BonnyCI is an open source, continuous integration (CI) project that offers developers parallelized tests, gated code merges, and the ability to build/test software projects with cross repository dependencies. BonnyCI provides 'Project Gating-as-a-Service', spawning independent pipelines that ensure the correct order of code changes in parallel.  This 'gating system' is based on Zuul, which was designed to handle the workflow of the OpenStack project.


Final Copy (Short)
==============
BonnyCI is an open source continuous integration project that provides developers 'Project Gating-as-a-Service', which spawns independent pipelines that ensure parallelized tests, gated code merges, and the ability to build/test software projects with cross repository dependencies, on demand.
