### ISSUE TITLE
zuul webapp reconfigured to use 127.0.0.1, github can no longer deliver webhooks

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#117]
https://github.com/BonnyCI/hoist/pull/116 changed the default zuul listening address from 0.0.0.0 to 127.0.01, for purposes of reverse proxy'ing the zuul status data behind apache.  This had the side effect of breaking all github webhooks as they're being delivered to http://zuul.bonnyci.org:8001/connection/github/payload

**Comment by jamielennox** [comment]
Ergh, why do those use the same variables? They should be unrelated,

**Comment by gandelman-a** [comment]
Sorry, I didnt get the commit linked to this issue but it was solved /w https://github.com/BonnyCI/hoist/pull/132 and github project configs have been updated so their webhooks post to :80 there.
