### ISSUE TITLE
bastion has no clouds.yaml content

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#119]
It appears that at some point, the bastion stopped getting clouds.yaml content, because the important info to do so was placed under inventory/groups_vars/production, but bastion is not a member of production.

Because the cronjob used by ansible-runner for system-ansible is the one that makes use of the bastion inventory, the hostname is set to "localhost", which means we could solve this by creating a inventory/host_vars/localhost, however, the system-ansible cronjob also exists in vagrant and (maybe) docker, so they would also attempt to source our real cloud from secrets (and probably fail).

**Comment by missaugustina** [comment]
Is this completed now?

**Comment by rattboi** [comment]
Oops, yep. Fixed with https://github.com/BonnyCI/hoist/pull/135
