### ISSUE TITLE
Update docs for github integration

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#122]
We have docs at http://bonnyci.org/lore/end_users/setup/ that explain the setup process. This will all change once we move to a GitHub Integration. So the docs will have to be updated, which is part of this milestone.

**Comment by mlangbehn** [comment]
The lore has moved to it's new, more professional home: http://bonnyci.org/lore/end_users/setup/

**Comment by omgjlk** [comment]
This was completed by https://github.com/BonnyCI/bonnyci.org/pull/62
