### ISSUE TITLE
Document the zuul status page

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#123]
We provide links to the status page, but don't really explain what it is users are looking at. We should have some text in our Lore that explains the status page.

**Comment by missaugustina** [comment]
Looks like this hasn't been updated in awhile. What's the status on this?

**Comment by mlangbehn** [comment]
This issue was resolved by BonnyCI/bonnyci.org#21 and clarified in BonnyCI/bonnyci.org#37.

**Comment by ConsoleCatzirl** [comment]
We have a minimal description of the status pages at http://bonnyci.org/lore/end_users/status, closing.
