### ISSUE TITLE
Verify deploy from scratch in new cloud

### ISSUE THREAD

**Issue by SpamapS** [BonnyCI/projman#128]

**Comment by jasontclark** [comment]
I'd like to help out with this one.

**Comment by missaugustina** [comment]
Sorry for not catching this sooner! I think this may depend on us being in the new cloud environment so it might be blocked. I've moved it there until we get confirmation that this is ready to be worked on.

**Comment by missaugustina** [comment]
09:28 <+ jlk> jasondotstar: auggy: I think ticket 128 is going to be a catch-all place for the issues we run into once we attempt a from-scratch deploy. We don't know what's broken until we try it, and then we'll have numerous things to fix.

**Comment by missaugustina** [comment]
Blocked pending a from-scratch deploy on the new cloud.
