### ISSUE TITLE
Implement ansible automation for provisioning production projects and accounts

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#134]
https://github.com/BonnyCI/bonnyci.org/pull/34 is the spec for our production accounts and projects. We'll need ansible to bootstrap our new cloud accordingly, once that merges

**Comment by eggshell** [comment]
@gandelman-a any objections to me picking this one up?

**Comment by missaugustina** [comment]
Moved to blocked because this needs another review before it can move forward. Looks like @j2sol needs to approve the latest round of changes. Once the last round of changes has been reviewed, then move this back to "in progress".

**Comment by missaugustina** [comment]
Moved out of blocked because it looks like it's still in progress.
