### ISSUE TITLE
Port github patches to zuul v3

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#136]
v3 has a new framework for drivers, and the github code on 2.5 needs to be ported and changed to work with v3. This ticket will track that work.

**Comment by ConsoleCatzirl** [comment]
I've compiled the following list of SHAs to port with the command `for rev in $(git rev-list ^master github-integration) ; do if ! test $(grep -c parent <(git cat-file -p $rev)) -gt 1 ; then echo $rev ; fi ; done`

```
c04be0e97ee2ff17d3111062aae3d093334fcebe
00ce32edd3d698361da84fd4654eac80ad589872
4a1b3e8daa17226fcf38577d03f6c5468d6fa62e
5b63e947e525ab4aedc67c1a142f9b223ee60aa8
32645f0d9339c66b6249047c504abb71199ef5c2
0608e98767aae30632f59a933359634b5b5f1eb5
2882692dfb4e2d59f6789d1a6364fdac09f690d7
dbb2a1816f0f778cc97f2d94da6012b2a976a3f1
d1cc9f49e707685d46c3f81ba7c66f3dfd7c26c8
249cb1a6a555876da228c973db5d0f42c5a65490
b88c5a1c053dc503a0fdace724b05befd64835cd
e7edd6396263e1143d97ac861fd2db9a529da6db
95d1656708084784db245e02cc4e6027ac3d9c06
c1105d55a260a876c40da42a0a47dc99cba1deac
53df294a9c8116f8a268951b3c37ccb9992f2e15
21062da0622d15da680f74a85d462cd3787edd4a
25206c1c358a20156590f90fe9cf37bb3e099c31
31942139462a6c33f11fab5b7bc7d3d70b89c4a7
d82cf74b8a23ee6a105fcd53b602c45c906d397c
7594599af1716c1ef9ba89aaf68a7b4132969197
37f6f5e7d6275bc9178acc9090edb4b67b5e49a3
6f1363b3057c179cb7331aa6a22ad3fba3d6cac4
b39f0d88c7409c296753f81f30868557991cbf52
7b09582bec8171ecb3e6553a93109156e0f0d705
df3515d3b411b3d01f0653d0491e2df5cef0d40c
94f9b17ecd5eda0e5a42b37c2c18fe4c0820d79e
dcaa3e1c93fcd3a605ed109959478e64ff2b601a
1e4db84963e5efee06c5a95acf6494e8ae581fa2
6a9ef27b20c03ae7282bd136d068ebd1582fc156
91f4fb81232a7add1b579497c6413c5b1ffbac86
b4f05a5bec3b9309076328b603eb8f2dbd78297a
25d687e472582afae287ecbe3a36470ef0fd1394
df04136051301f664b45b109c9ce8fedd18904ed
137a79517da90a03b11d379f06297bea92da0c9a
67ce3af1f4decf35c657e1ddca9860f0ebf7cf17
0544937b653ee30add8ec99e4a24c51e220e4a38
59828f8d2e13ed813632d9993a32c5add436f4c8
f13e8832789dabdc2b730eb58752a448ccfc21d4
2e70eeef1b6f293c39f4d578f82dcf8b04caa9dc
672d69aa4a66d31ea7638388106a6233eef8343f
1ae8cdb6377de8c58dd1af97a7e3858e2d1164e2
ae57d099b141703bbd4dcf51bc9b123876cd0deb
```

Which is the list of non-merge commits in the github-integration branch but not in the master branch.

I propose that we attempt to cherry-pick those in reverse order (from the bottom up) onto the feature/zuulv3 branch.

**Comment by SpamapS** [comment]
Another data point is that we may want to pile on this story in v3 before we get too deep into this: 

https://storyboard.openstack.org/#!/story/2000781

This changes the data model inside Zuul to be more favorable to writing non-Gerrit drivers, and may allow factoring out some of the changes that reach into Zuul below the driver layer.

**Comment by omgjlk** [comment]
Discussed with Zuul upstream on IRC.

Strategy:
@SpamapS will start on the Changeish refactor into a parent Ref class. I'll be collaborating and reviewing as it happens.

I will be working on creating a patchset for the feature/zuulv3 branch that is a port of the code on v2.5 upstream and in our repo, squashed where appropriate, but still a series of patches to review instead of one massive change. I'll try to use the commits where I can so authorship is retained.

**Comment by omgjlk** [comment]
Grabbing patches starting at `8daec1149cd78c2d6451864669c1c663afddc26f`

**Comment by missaugustina** [comment]
Dependent task identified in planning: need to deploy a Zuulv3 so that we know we have something that works. That way when we break it, we at least have the confidence that it used to work.

**Comment by missaugustina** [comment]
Is this work part of this story? https://storyboard.openstack.org/#!/story/2000774

**Comment by omgjlk** [comment]
It appears so!

**Comment by omgjlk** [comment]
https://review.openstack.org/439831 and https://review.openstack.org/#/c/439834/ are up now for review.

**Comment by omgjlk** [comment]
Some feedback from upstream:

[10:25:09]  <jeblair>	00:42:28> jlk: your request for early review is entirely reasonable, and i'd like to help.  but as i try, i'm honestly not sure how to proceed.  i can do a half-assed review and say "yes/no good/bad general direction" and then do a real review later where we change all kinds of interfaces, etc (and i may still be wrong).  or i can do a real review which involves a major context switch and time investment.
[10:25:09]  <jeblair>	00:45:15> jlk: i don't feel like we have achieved enough forward progress on the major milestones which are ahead of the github milestone to be able to afford doing that at this point.
[10:25:09]  <jeblair>	00:51:44> jlk: i can't see a cursory review being helpful.  you're likely to just get upset that i'm not being consistent.  :)
[10:25:09]  <jeblair>	00:57:07> my hope was that you would be able to do the bulk of the porting work now, and then once we cleared out more of the work ahead of it, we'd both have time to dig into refining the series.


So upstream guidance is to carry on porting patches, and hopefully get something working with v3, and as v3 firms up we'll start reviewing how things look and re-arrange as necessary.

**Comment by omgjlk** [comment]
https://review.openstack.org/443323 is up too.

**Comment by omgjlk** [comment]
https://review.openstack.org/#/c/443947 adds push and tag events.

**Comment by omgjlk** [comment]
https://review.openstack.org/443959 adds comment event.

**Comment by omgjlk** [comment]
https://review.openstack.org/444034 adds support for git over ssh.

**Comment by omgjlk** [comment]
https://review.openstack.org/444060 is the initial support for setting commit status.

**Comment by omgjlk** [comment]
https://review.openstack.org/444463 adds the ability to merge PRs

**Comment by omgjlk** [comment]
https://review.openstack.org/444511 adds the ability to trigger on label add/remove as well as report via add/remove labels.

**Comment by omgjlk** [comment]
https://review.openstack.org/445242 adds dequeue support

**Comment by omgjlk** [comment]
https://review.openstack.org/445292 adds dependent pipeline support (gate)

**Comment by omgjlk** [comment]
https://review.openstack.org/#/c/445625 adds triggering on specific branches

**Comment by omgjlk** [comment]
https://review.openstack.org/#/c/445644 updates reporting message to include user details

**Comment by omgjlk** [comment]
https://review.openstack.org/446113 adds file matching support.

**Comment by omgjlk** [comment]
https://review.openstack.org/446150 logs API rate limits

**Comment by omgjlk** [comment]
https://review.openstack.org/446782 allows filtering status page on PR/Change in the URL, and supports sending that URL.

**Comment by omgjlk** [comment]
Need to implement functionality to load zuul config bits from project repos, and list the project repos in the main.yaml file. Currently throws a `NotImplemented` error when trying to discover what branches exist.

**Comment by omgjlk** [comment]
https://review.openstack.org/448257 filters changes by trigger type. Allows multiple drivers in the same zuul.

**Comment by omgjlk** [comment]
https://review.openstack.org/449258 adds support for github enterprise.

**Comment by omgjlk** [comment]
https://review.openstack.org/449365 adds triggering on positive pr reviews

**Comment by omgjlk** [comment]
https://review.openstack.org/449390 adds support for requiring status on pr HEAD

**Comment by omgjlk** [comment]
https://review.openstack.org/#/q/topic:github-v3 has been rebased after much work.

There are two more things from our tree I plan to cherry pick:
27df6082bea0f825ae5c5963178196ab63be087d
bae8b9c5cfc7c0e2d1965bfaa91239662deb3c90

There is also the Github Integration set of patches I'm asking @jamielennox to take a pass at:
cc1165171b0b3517126c5c05e1d87337be383208
6ba1dfe88531abb8410e703d7e4c03c688962888
d306581148b3294edc40fa087f33bf77b869b27c
04645f4de192fbadb63f4905cf48e4447d2cb9ec
77a03a0c3ad8c6e41c522e28c81c51411e9d0575
21062da0622d15da680f74a85d462cd3787edd4a

**Comment by omgjlk** [comment]
We had a meeting with Zuul upstream to go over some initial feedback on the patch set. It was decided to change a few things with regard to how the events are referenced in the layout.

There will be one event, `pull_request` with a variety of `action` options, such as `opened`, `reopened`, `comment`. Additionally there will be a `push` event that uses regexes to capture either a branch push or a tag push.

For reporting, it was decided to allow the `status` report option to enumerate which status to set, selecting from `pending`, `success`, or `failure`. This would allow a pipeline to set `success` status on a failed run to avoid "voting" on the PR. Disabling comments will be allowed, but the default should be that comments happen. One must opt to disable comments on reporting.

For requirements, we should move the GitHub specific pipeline requirements to be trigger requirements instead, as triggers are source/driver specific. There it will make more sense to have the requirements for any given source.

Some output is in the ether pad https://etherpad.openstack.org/p/7HFyMRf519

**Comment by omgjlk** [comment]
This is all done.
