### ISSUE TITLE
Poop Deck lacks automation

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#138]
The poop deck doesn't automatically get updated for things like an issue closing. This task would be to create a webhook that would move the cards into the appropriate columns when certain activities happen.

See: https://developer.github.com/v3/projects/cards/#move-a-project-card

GOALS:

The solution that we implement should:

- Move cards into Done when they are closed
- Move cards into "in progress" when a pull request is linked or it is assigned to someone
- Add new cards to Backlog when an issue is created
- spec out any other events that should trigger card moves or just check this off if you can't think of any

Which services will we research:

- [x] [ZenHub](https://www.zenhub.com/)
- [x] [Waffle.io](https://waffle.io/)
- [ ] [Huboard](https://huboard.com/)
- [ ] [Zube.io](https://zube.io/)

**Comment by missaugustina** [comment]
Moved to the top of TODO since this is affecting us more directly right now.

**Comment by jasontclark** [comment]
I'm going to take a stab at this one. FYI.

**Comment by SpamapS** [comment]
Making myself available if you need help. :)

**Comment by jamielennox** [comment]
The three real competitors i know of here are: 

- https://www.zenhub.com/
- https://waffle.io
- https://huboard.com

Zenhub was somewhat hated in pyrrrat cloud - but that was largely because that was on github enterprise and so you could only download a specific addon, that was completely unsecured, and only worked in some browsers. I don't think that should be a reference for Bonny.

**Comment by jamielennox** [comment]
https://zube.io/ seems to be another - and now i'm going to stop looking at this stuff.

**Comment by SpamapS** [comment]
This issue has now morphed from doing webhooks to move cards, to possibly migrating to something else. I'll stay assigned and try to do some analysis of the mentioned tools.

**Comment by jasontclark** [comment]
Updated the original description of this card to indicate which tools we will research.

**Comment by jasontclark** [comment]
Tools Analysis Table:

| Tool | 'Moves to Done' | 'Moves to In-Progress' | 'Adds to Backlog' | 
|-----|------------------|------------------------|------------------|
| ZenHub | | | |
| Waffle.io | 👍  | 👍 | 👍  |
| Huboard | | | |
| Zube.io | | | |

**Comment by SpamapS** [comment]
It is what it is. :-/
