### ISSUE TITLE
Develop an IRC channel logging solution.

### ISSUE THREAD

**Issue by jasontclark** [BonnyCI/projman#156]
In an effort to ensure the devs and customers alike have a way to search through our primary mode of communication, develop a way to have the #BonnyCI IRC channel logged.

**Comment by jasontclark** [comment]
@rattboi Need to catch up w/ you on this

**Comment by rattboi** [comment]
@jasontclark This should just be part of whatever IRC bot we start using.

**Comment by rattboi** [comment]
The standup bot issue will track bot ideas/solutions. bonnyci/projman#150

**Comment by jasontclark** [comment]
Talked to @rattboi about this.  The original idea was to go with hubot, but the general consensus across the team is to go with something Python based.  Currently evaluating these two tools:

* [errbot](https://github.com/errbotio/errbot)
* [sopel](https://github.com/sopel-irc)

**Comment by missaugustina** [comment]
Did another conversation happen? I remember we all said it didn't matter whether it was Python based or not and we were all fine with Hubot/JS.

**Comment by jasontclark** [comment]
@rattboi has tested Errobot.  Looks to be a viable solution for us.  Tweaking the configuration to eventually create an Ansible playbook to deploy a micro instance in our new cloud env. to provide this service.

**Comment by rattboi** [comment]
I've made progress on this. I'll be adding it to the extensions repo shortly. Use is blocked by #175 and #176.
