### ISSUE TITLE
zuul-cloner fails to import requests

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#160]

**Comment by ConsoleCatzirl** [comment]
When we changed to installing github3.py manually to use a specific sha, we failed to update the nodepool image elements to also install github3.py, which pulls in requests as a dependency.

**Comment by gandelman-a** [comment]
https://github.com/BonnyCI/hoist/commit/f1b501b02d8eb14d600a43b9321b27ad0db1d35f
