### ISSUE TITLE
service outage: apache down on zuul host

### ISSUE THREAD

**Issue by loafyloaf** [BonnyCI/projman#161]

**Comment by loafyloaf** [comment]
outage occurred on 7mar2017.  I'm a bit sketchy on the details, but something to the effect of apache on zuul have a new key but an old cert, which knocked out SSL and therefore zuul services

**Comment by missaugustina** [comment]
I think the details are in Issue #158

**Comment by ConsoleCatzirl** [comment]
We need to monitor the apache process
