### ISSUE TITLE
Research backend options for ARA

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#173]
Right now, we are using ARA with the sqlite backend, which has a few negatives:

1) The permission setup so that www-data, cideploy, and root can all get to the file is annoying and maybe a bit insecure?
2) Maintenance of the sqlite database is mostly not managed by ARA. There's a 2-step process for removing old results, but it takes a long time. Also, the sqlite database isn't auto-vacuum, so it needs another sqlite3 command to vacuum to shrink the space used. This may have the side-effect of performance issues with the sqlite db.

Using mysql, which we already have a role for, would avoid the permissions issue, as we would inject creds into each config. I also assume there may be better performance characteristics, but I'm not positive on that.

**Comment by missaugustina** [comment]
How much data do we currently generate with ARA logging and do we have any metrics to track it over time so we can gauge capacity needs? Also what are the impacts if this database gets full, fails, or is slow? Will it affect BonnyCI availability or does it just mean we would have incomplete ansible logs?

**Comment by rattboi** [comment]
ARA generates about 64 mb of database per day, if it is linear (we have two days worth, so it's hard to get a general trend). We don't have metrics in place at this point. 

If the database gets full, it will affect our CI ability, as it exists (and must exist) on the same host as our ansible runs.

As mentioned in 2 above, I know the process for removing old results, so the workaround for now is to implement that in automation. However, I do think this is worth circling back to for a better long-term solution.

**Comment by rattboi** [comment]
https://github.com/BonnyCI/hoist/pull/357 is a stop-gap to deal with the massive sqlite db we have now.

I'm going to start actively working the real solution for this, as ARA has found a few errors for us, and having is be usable would be to the benefit of us all
