### ISSUE TITLE
Collect uptime metrics

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#187]
We should have various numbers describing our uptime.

**Criteria:**

- [ ] Uptime information is sent to datadog
- [ ] Some basic alerts are in place

**Comment by loafyloaf** [comment]
so, datadog collects a boat-load of metrics, both from the 'physical' machines we monitor, as well as services checks and other uptime stats through their integrations (apache, zookeeper, etc).  We have basic alerts set up for all hosts.

**Comment by mlangbehn** [comment]
@loafyloaf added me to our DataDog team, and I am now able to see what is being sent and how to access it.

**Comment by mlangbehn** [comment]
Among the metrics we are already sending to DataDog are system uptime and service availability. I had been reading this issue as requesting that system uptime be sent to DataDog, but that is less useful for us than service availability.

Here is our current status page: https://p.datadoghq.com/sb/cbf19e221-1b77fb05f2
I will look into specific monitors or alerts that may be helpful to add.

**Comment by loafyloaf** [comment]
I'm going to call this complete.  Further monitors/alerts should probably be detailed in separate issues.
