### ISSUE TITLE
Create a comprehensive onboarding document for contributors

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#19]
Per issue #18 a README was created but it is far from complete. To consider this issue resolved, the onboarding document must:

- [x] contain step by step instructions for creating a development environment

- [x] docs for setting up environment with a vm

- [ ] docs for setting up environment with docker

- [x] explain the code submission and review process

- [x] provide guidance for code submissions

- [x] how to add a repository to BonnyCI

- [x] provide community details including where to talk about issues, community meetings, or other areas where project communication happens

- [x] be tested out by someone other than the committer

**Comment by missaugustina** [comment]
Removed help wanted cuz it looks like folks are on this

**Comment by eggshell** [comment]
This has been closed. Refer to [this lore issue](https://github.com/BonnyCI/lore/issues/4) for more history and PRs for each step.
