### ISSUE TITLE
Documentation: Personal Cloud Accounts refers to non-existent file "create-users-projects"

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#196]
This page: http://bonnyci.org/lore/developers/dev-environment/personal-cloud-accounts.html

refers to:
https://github.com/BonnyCI/hoist/blob/master/create-users-projects.yml

That file doesn't exist. Perhaps it's supposed to be create-cloud-resources instead?

**Comment by mlangbehn** [comment]
@jasontclark please update on the status of this issue.

**Comment by jasontclark** [comment]
Moved to DONE.
