### ISSUE TITLE
Investigate adding github hook support to quartermaster

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#197]
We discussed previously having the github events go through the bot in order to have more control over the format of said events. 

These would be along the same lines as the IRC notifications we already get when pushes/merges happen, etc, except we could show them in a more concise manner. There are also possibly other events that we can tap into, if we are interested. 

https://github.com/errbotio/err-githubhook already exists, so we could start from there and add whatever we needed.

**Comment by SpamapS** [comment]
This ticket lacks information for what said github hooks would do.

**Comment by mlangbehn** [comment]
@rattboi: Please update the issue description per @SpamapS's comment.

**Comment by rattboi** [comment]
@mlangbehn ok, ticket description updated

**Comment by jamielennox** [comment]
I'd be interested in something that can turn a datadog webhook into an IRC message. errbot/quatermaster would be a likely place for that as well.

**Comment by SpamapS** [comment]
no more quartermaster :-P
