### ISSUE TITLE
Failed merges should use a non-default failure message

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#199]
We currently post back a message when tests fail, with a link to test output for debugging.

We also post back a message if Zuul cannot merge an approved patch for whatever reason, see: https://github.com/BonnyCI/hoist/pull/274
 
```
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.
```

This is a default message in Zuul and can be configured.  We should instead use a custom message with a link to a page on bonnyci.org that briefly describes the various scenarios that would cause this, so the users have some idea of what happened.

**Comment by eggshell** [comment]
I've taken a look into this and it should involve two simple pull requests:

- [x] documentation page under the `use` section of bonnyci.org which lists the possible scenarios for merge failures and how to troubleshoot them.

- [x] modification of BonnyCI/hoist which modifies `layout.yaml` to use the merge failure message in the check and gate queues.

**Comment by eggshell** [comment]
Both of the PRs have merged, so this can be closed out and moved to Done.
