### ISSUE TITLE
CI failures on Zuul role

### ISSUE THREAD

**Issue by mlangbehn** [BonnyCI/projman#212]
Currently, `hoist/tests/test-hoist-ansible.sh` is failing:

```text
TASK [zuul : Install job definitions] ******************************************
task path: /home/travis/build/BonnyCI/hoist/roles/zuul/tasks/launcher.yml:10
fatal: [allinone]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no --chown=zuul:zuul --blocking-io --rsh='/usr/bin/docker exec -u root -i' --out-format=<<CHANGED>>%i %n%L /home/travis/build/BonnyCI/hoist/roles/zuul/files/jobs/ allinone:/var/lib/zuul/jobs/", "failed": true, "msg": "rsync: Failed to exec /usr/bin/docker exec -u root -i: No such file or directory (2)\nrsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.0]\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in IPC code (code 14) at io.c(226) [sender=3.1.0]\n", "rc": 14}
```

**Comment by mlangbehn** [comment]
This is issue is impacting tests being run in both [BonnyCI][1] and [Travis CI][2].

[1]:https://logs.bonnyci.org/check_github/BonnyCI/hoist/333/1492098119.86/bonnyci-run-check-multinode/console.html#_2017-04-13_15_46_33_366541
[2]:https://travis-ci.org/BonnyCI/hoist/jobs/221383850#L1481

**Comment by gandelman-a** [comment]
So this ended up being related to a new upstream ansible. We were previously vendoring a plugin to workaround  a bug. The bug was fixed in the new upstream release, but the new release was also incompat with our in-tree plugin.  Simply dropping the in-tree plugin fixes it.
