### ISSUE TITLE
nodepool DIB builds should validate themselves

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#215]
In discussion about recent DIB upstream breakages, we have an idea!

As part of our bonnyci DIB elements, we should have a late-running script/task that does some validation of the image during build time. This could include:

* checking that we have a functioning python environment and things like virtualenv function 
* checking that the zuul-cloner that we install can load and do something (a simple zuul-cloner -h should make sure all its imports are functioning properly)

There may be a few other things that we install or depend on that will bite us at runtime if they are not functioning properly.   This is something we can maintain over time as we add new things to our images.

A script could be added to a new directory 'cleanup.d' that will run late in the build process and fail the build if it fails.

**Comment by ConsoleCatzirl** [comment]
This is in response to #214
