### ISSUE TITLE
Implement our backup plan

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#218]
Implement our [backup plan](http://bonnyci.org/lore/admins/backups/)

**Comment by ConsoleCatzirl** [comment]
This is being implemented in BonnyCI/hoist#335

**Comment by ConsoleCatzirl** [comment]
- [x] Create ansible roles for backup clients and server
- [x] Configure list of backup source directories
- [x] Allow backups to happen at various times and intervals
- [x] Test restoring from backup
- [x] Delete expired backups

**Comment by jasontclark** [comment]
Added myself from a documentation perspective.

**Comment by ConsoleCatzirl** [comment]
Restoring from backup does not remove files not in the backup, it only affects files in the archive.

I think this is fine for now, and if we decide we want to purge files not in the archive we can add that as a task in the restore playbook.

**Comment by ConsoleCatzirl** [comment]
I think we can call this done
