### ISSUE TITLE
Vagrant-deploy is ignoring optional arguments

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#238]
Following the lore, I attempted to limit a vagrant ansible run to a specific host, and instead it ran the entire run for all vagrant hosts.

Command run: './tools/vagrant-deploy.sh --limit bastion'
Expected: runs the install-ci playbook against only the bastion.
Actual: The entire playbook is run against all vagrant hosts.

**Comment by mlangbehn** [comment]
Testing fix. Will open a pull request shortly.
