### ISSUE TITLE
Vagrant-deploy is slow to run when hosts are already started

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#239]
vagrant-deploy.sh uses 'vagrant up' every time you use it. It's good to run that when your hosts aren't provisioned and running, but when they're already running, it's about 1:30 of wait time before the playbook can start running.

**Comment by mlangbehn** [comment]
I solved this problem once a few years ago, and it was kind of ugly. I'm going to take a little time on this one and try to make it a bit nicer this time...
