### ISSUE TITLE
Unsafe/annoying to restart standup bot because of in-mem state

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#241]
There's a few things that are kept in-memory that means that we have to be careful when we restart the bot, as the in-mem things are lost. This leads to double notifications for some people, and loss of in-progress uncommitted standups.

**Comment by rattboi** [comment]
Moving all this state to sqlite seems the easiest route to me, and should protect us from the above issues.

**Comment by SpamapS** [comment]
Unfortunately, standup bot is dead. Closing.
