### ISSUE TITLE
Figure out production monitoring

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#26]
_From @missaugustina on November 23, 2016 21:41_

What metrics and monitoring would this need in production?

So far we've come up with:
- zuul: merger count
- nodepool:
    - total instance count
    - ratio of (building + deleting) to (ready + in-use) instances

_Copied from original issue: BonnyCI/hoist#102_

**Comment by jamielennox** [comment]
Repo created with monitors at https://github.com/BonnyCI/datadog-monitors/ based on tool at https://github.com/BonnyCI/datadog-builder

**Comment by missaugustina** [comment]
I'm closing this because we have individual issues that are addressing specific monitors.
