### ISSUE TITLE
We need some Data Dog Dashboards (DDD?)

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#27]
_From @missaugustina on November 23, 2016 21:40_

For now, we need something for current developers built around monitors. Down the road we'll need something for operators.

_Copied from original issue: BonnyCI/hoist#101_

**Comment by loafyloaf** [comment]
high-level status dashboard available here:

https://p.datadoghq.com/sb/cbf19e221-1b77fb05f2

**Comment by loafyloaf** [comment]
other boards:
zuul - https://p.datadoghq.com/sb/cbf19e221-f4857162ed
nodepool - https://p.datadoghq.com/sb/cbf19e221-504328f60a

note: these are the public urls for these dashboards.  anyone in our group should also be able to see them listed under 'Dashboard List' in their datadog account

**Comment by missaugustina** [comment]
I'm going to close this out for now since it looks like we got a first stab at this. We can file specific issues for any additions we need to make. Feel free to reopen it if I've closed it prematurely, I'm just swabbing the Poop Deck over here ;)
