### ISSUE TITLE
Get a Blue Box Cloud

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#3]
We need a cloud to run our services on (public facing) as well as capacity for node pool. Our options so far have not panned out, a blue dollar Blue Box Cloud may be just what we need.

We have to figure out sizing of it first.

**Comment by omgjlk** [comment]
I have sent mail inside of Blue Box to get details about the process.

**Comment by missaugustina** [comment]
Per last planning meeting, looks like the next step is to follow up with Colette and find out if there's anything we need to do on our side. 

11/23: 
- jlk: on hold, right ppl are talking, quote in colette's hands, flying under the radar on current clouds, haven't hit capacity yet, so not immediate concern
- currently on a shared bluebox, how much capacity do we have? jlk: we have a quota... looking it up, jlk to provide deetz
- greg: need a setup so we can run 10ish test nodes
- jkeating: 20 instances, 30 cpus, 51200 mb ram, (the cloud itself has at the moment another 50 cpu available)

**Comment by omgjlk** [comment]
We have a cloud! We'll be using it soon.
