### ISSUE TITLE
Need an easy way to test changes locally

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#31]
_From @jesusaurus on November 21, 2016 19:57_

Developers should have an easy and simple means of local testing.

_Copied from original issue: BonnyCI/hoist#72_

**Comment by missaugustina** [comment]
I went ahead and assigned this since it sounds like you're playing around with Vagrant to make this a reality. I'm adding myself to it too since I'm trying to better document the setup steps.

**Comment by missaugustina** [comment]
_From @j2sol on November 23, 2016 1:47_

Some things I'm running into.

- monitoring calls that hit data dog will fail unless a secret key is in place. Need to skip those, but do the rest of monitoring.
- nodepool role default references a cloud not configured in example secrets
- bastion role requirement hardcodes a cloud not configured in example secrets

**Comment by missaugustina** [comment]
_From @j2sol on November 23, 2016 1:48_

This may be fixed, or partially fixed, by #93

**Comment by omgjlk** [comment]
https://github.ibm.com/OpenStackInnovation/hoist/pull/52 may also assist in fixing this.

**Comment by ConsoleCatzirl** [comment]
The vagrant environment is working pretty well for testing most moving parts, closing this.
