### ISSUE TITLE
zuul, nodepool, other service logs need to be exposed somewhere

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#33]
_From @gandelman-a on November 17, 2016 18:7_

Zuul and nodepool are both running on nodes behind the bastion.  Their log files, and those of other services running on those inner nodes, need to be exposed somewhere to the outside world.

_Copied from original issue: BonnyCI/hoist#49_

**Comment by missaugustina** [comment]
This looks like it's a duplicate of Issue #28

**Comment by ConsoleCatzirl** [comment]
Issue #28 has a larger scope than this issue, this is more of an implementation of a single subtask of #28

**Comment by ConsoleCatzirl** [comment]
We now put zuul and nodepool logs in an ELK stack on the logs host.
