### ISSUE TITLE
First-time setup of inventory hosts from bastion cron causes failure (known_hosts)

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#34]
_From @rattboi on November 16, 2016 2:13_

When ansible attempts to connect for the first time to a host in the inventory on a new bastion, the known_hosts file is missing entries for these hosts, and attempts to interactively ask if you're ok with the host key.

Since this is from cron, the interactive aspect fails, and so the hosts are never properly registered.

Note that this is default behavior in ansible.

More info here: http://docs.ansible.com/ansible/intro_getting_started.html#host-key-checking

_Copied from original issue: BonnyCI/hoist#38_

**Comment by omgjlk** [comment]
I think this was handled by https://github.ibm.com/OpenStackInnovation/hoist/pull/57

We'll re-open after our next complete tear down and rebuild if it is not fixed.
