### ISSUE TITLE
deploy user ssh keys need to live somewhere

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#35]
_From @gandelman-a on November 15, 2016 22:52_

this could be part of https://github.com/BonnyCI/hoist/issues/18

when provisioning a bastion from scratch, the deploy user (currently 'cideploy') needs ssh keys generated or installed so that it can reach the infrastructure its managing (the zuul and nodepool nodes)

we can add this to secrets.yml (or whatever that turns into), but the cideploy user is managed as a normal bastion_user in roles/bastion/, and not as a special cased deploy user with ssh key management.

_Copied from original issue: BonnyCI/hoist#33_

**Comment by missaugustina** [comment]
What's the current status of this issue? Did it end up being resolved or is it still open?

**Comment by gandelman-a** [comment]
Fixed with https://github.com/BonnyCI/hoist/commit/6fb24df050d0101e79c9604f778084f7eeb62081
