### ISSUE TITLE
Improve pip role

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#36]
_From @j2sol on November 14, 2016 20:55_

There are a couple issues with pip role that should be addressed:

- [ ] pip install script is downloaded and executed without any validation
- [ ] pip install script is ran every playbook execution

We should discuss how to address these in the near future.

_Copied from original issue: BonnyCI/hoist#20_

**Comment by missaugustina** [comment]
_From @SpamapS on November 16, 2016 22:32_

Vendored and done

**Comment by missaugustina** [comment]
_From @rattboi on November 16, 2016 23:27_

Vendored, but needs some improvements.

**Comment by omgjlk** [comment]
Can we get clarity in what needs to be improved before moving?

**Comment by missaugustina** [comment]
Assigned to @rattboi because it looks like he's working on it based on his last comments. If this is not correct, then feel free to re-assign to the correct person.

**Comment by missaugustina** [comment]
What's the current status of this issue? The last question was never answered, what steps are remaining?

**Comment by rattboi** [comment]
Ah, right. I dropped the ball on this one. 

The main issues I had with it were that it used to be non-idempotent, which seems to be solved. The other is that we don't do any validation that it's the file we expect it to be (hash sum or something). That is still the case, but it's probably not a big worry. I'm just gonna close.
