### ISSUE TITLE
Improve secrets management

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#37]
_From @j2sol on November 14, 2016 20:46_

Currently we have a plain text secrets file that we hand copy from bastion to bastion. This is a bit scary as it sits in plain text on whatever filesystem it happens to be copied to.

I propose we instead encrypt this file with ansible vault. This allows the file to remain encrypted at rest, and we simply have to write a passphrase to the filesystem of the bastions so that cron executed jobs can read the file. Any backup we make of the file will be encrypted.

We'll put aside discussion of where to store/backup this file for a later discussion.

The new bastion flow would be:

1) Use hoist to boot new instance with an ssh key you can use
2) Log into new instance and put secrets file in place and write passphrase to expected path
3) execute remainder of hoist on the bastion, enabling it to self-update

As new people are on-boarded we can communicate the vault passphrase to them. As people leave, we can rotate the secrets inside the vault, and rekey the value itself, communicating the new passphrase to the remainders.

Part of this is we will need to track all the secrets and use Ansible to write them out to the filesystem, rather than hand copying a bunch of files.

- [x] deploy ssh keys

- [x] clouds.yaml

_Copied from original issue: BonnyCI/hoist#18_

REMAINING WORK:

- [ ] Back it up
- [ ] Track changes (at least indicate when it was edited and what was changed, even if old value is not tracked)

**Comment by missaugustina** [comment]
_From @j2sol on November 18, 2016 0:29_

Secrets are now vault protected on the filesystem, with just a passphrase written out. Other work related to this issue can continue.

**Comment by missaugustina** [comment]
Notes from last planning meeting:

- next steps? brought credentials into a single place but encrypting the file made things more complicated, does it need to be encrypted? what's next?
- what if we just don't encrypt the file right now?
- shouldn't be in the gitrepo, but it's convenient; where else should it be?
- encrypt it once, copy it to where it was, decrypt, then make ansible vault not fire
- what about backups? no backups, but with encryption you can backup... what about password?

**Comment by omgjlk** [comment]
Current status:

- File is not encrypted
- File is not stored anywhere but on the production nodes
- It appears that all secrets are being stored in the one file and used from there to write out other files.

Future needs:

- Back it up
- Track changes (at least indicate when it was edited and what was changed, even if old value is not tracked)

**Comment by missaugustina** [comment]
I'm adding the Help Wanted label onto this one since it looks like it hasn't been touched in awhile. While the issue is currently assigned to @j2sol if someone else wants to pick this up then just touch base with him.
