### ISSUE TITLE
Test the CI

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#49]
- [x] Syntax check via TravisCI
- [x] Zuul layout check
- [x] Run CI twice, check changed is what we expect (might not be 0)

**Comment by missaugustina** [comment]
We still need these additional tests!

**Comment by missaugustina** [comment]
I updated the description to clarify that the changed stuff doesn't need to be 0, it just needs to be whatever we expect. The work in Issue #38 just needs to make sure it updates these tests if it changes anything.

**Comment by mlangbehn** [comment]
Thanks, @missaugustina.

**Comment by mlangbehn** [comment]
I will get back to this once I am finished with my other issues.

**WORK STILL TO DO:**
* Create a test to run the deployment a second time in CI
  * Test needs to verify the expected number of changed items

**Comment by mlangbehn** [comment]
Currently blocked by the issue with `[ zuul: Install job definitions ]` in CI.

**Comment by mlangbehn** [comment]
Removed the item to `Identify other tests and add them to the checklist (or create additional Issues and link them here)`, because that is an ongoing process and is therefore outside the scope of this issue.
