### ISSUE TITLE
Validate BonnyCI Deployment

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#50]
- forked Zuul with Github integration patches applied
- runs automatically when PR submit/reopen

- [ ] Gerrit sandbox no-op
- [x] Github sandbox no-op
- [x] Github echo true
- [ ] Redeploy from scratch
- [x] Hoist on BonnyCI
- [x] Github repo: Basic Python repo with tests
- [ ] Github repo: Python Crypto
- [ ] Github repo: Basic repo, non-python

**Comment by missaugustina** [comment]
Basic Python Repo with tests: checked against giftwrap (in project)

**Comment by omgjlk** [comment]
Not sure why this was added to https://github.com/BonnyCI/projman/milestone/2  Seems beyond the scope of the milestone itself.

**Comment by missaugustina** [comment]
We've tested BonnyCI with a variety of different projects and different scenarios so I think we're good here.
