### ISSUE TITLE
Figure out Key Management -  SSH user keys, deploy keys, host keys

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#51]
using deploy key from within ghe, having ssh key verification issues, tried to add the key back into hoist repo, said key already existed (same key was used with seedci repo), can only use one key per repo per org?

**Comment by omgjlk** [comment]
We're no longer making use of GHE, so we don't need that part any more.

As for cloning private repos from github, I believe we have a path forward with using integration tokens for short-lived access.

**Comment by omgjlk** [comment]
Is anybody still unhappy with the way ssh keys are managed (for bastion to nodes, and for zuul/nodepool interaction)?

**Comment by omgjlk** [comment]
Nobody was unhappy, closing.
