### ISSUE TITLE
Create a Zuul status web page (like OpenStack Infra)

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#52]
Generated by what's in zuul git, infra team does symlinking in puppet and throws it on apache

https://github.com/openstack-infra/puppet-zuul/blob/master/manifests/init.pp#L319

http://zuul.openstack.org/

**Comment by missaugustina** [comment]
I really think we should call it the "poop cabin".

Poop cabin - A room built on the top deck of a ship, often the Captain’s.

**Comment by omgjlk** [comment]
Picking this up to poke at.

**Comment by omgjlk** [comment]
Wow, so uh... this may be more work than it should be. jquery-visibiilty, graphitejs, twitter bootstrap, libjs-jquery, hard to tell what's required, what's part of zuul's built in status page, vs the one that infra builds up itself ( https://zuul.openstack.org vs https://status.openstack.org/zuul )

More investigation is needed, putting this back on the backlog.

**Comment by omgjlk** [comment]
This is now live!
