### ISSUE TITLE
Create ARA role for bastion

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#57]
The ansible logs on the bastion leave a lot to be desired. They are hard to read and figure out, especially after being stripped of color. 

ARA (Ansible Run Analysis) is a small set of tools to help with analysis of ansible runs. I've done some simple tests locally, and it is pretty slick.

Adding this to the bastion would be to our benefit, I believe.

**Comment by missaugustina** [comment]
What's the status of this?

**Comment by rattboi** [comment]
This is next in line for me. I misjudged my ansible abilities and didn't have a good testing workflow, but those are resolved, so I don't expect this to be too difficult.

**Comment by rattboi** [comment]
Made a lot of progress on this. Currently stuck trying to make it work nicely with apache AND our ansible-runner infrastructure. 

There's a bit of an issue because ara wants the temp files created by ansible to be readable by apache, but I don't think this is technically necessary. The only reason ara needs access to this is because it's using the ansible tmp directory for a little RPC between the ARA callback and the modules.

I'm thinking I'm going to ignore this and get everything else working well, and circle back if we decide we want to use the modules (ara_read/ara_record).

There's also issues w/ the ara WSGI app interacting with the virtualenv its installed into, so @jamielennox recommended using uwsgi. I've started researching that, and I think I know what I need to do. 

I have a WIP PR for what I have so far at https://github.com/BonnyCI/hoist/pull/202

**Comment by missaugustina** [comment]
If you decide to ignore this issue and put it aside, be sure to put it in the "blocked" column with a comment as to why.

**Comment by rattboi** [comment]
No, I'm not ignoring the issue, I'm ignoring something that would block us, and coming back to it at some later date. I'll file an issue about that though.

**Comment by missaugustina** [comment]
Could you link the issue you created? Either mention that one here or this one there. Thanks!

**Comment by rattboi** [comment]
https://github.com/BonnyCI/projman/issues/173 is the issue tracking what is lacking with the current role/configuration.
