### ISSUE TITLE
Errors running check_hoist -- certificate invalid

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#69]
Seeing this failure in our check_hoist runs: http://logs.bonnyci.com/check_github/BonnyCI/hoist/43/1483938142.11/ubuntu-hoist/console.html#_2017-01-09_05_04_13_536129

```
"msg": "Failed to validate the SSL certificate for bootstrap.pypa.io:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: getrandom() initialization failed. (_ssl.c:590).
```

This is blocking our testing of our own repo.

**Comment by jamielennox** [comment]
Should be fixed by BonnyCI/hoist#46.

Basically we didn't have enough entropy in the newly booted vm and so the SSL handshake failed. I also added ansible/ansible#20025 for better debugging information here.
