### ISSUE TITLE
Github integration trigger on X-GitHub-Event: pull_request_review

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#73]
Github sends a `X-GitHub-Event: pull_request_review` when somebody adds a pull request review. We would like zuul to react to this as a potential trigger for things like check/gate.

Details at https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent

**Comment by omgjlk** [comment]
For simplicity sake, we should only trigger on a status of `APPROVED`.

**Comment by j2sol** [comment]
Looking at the code, we'll need to create the `_event_pull_request_review` method in `zuul/connection/github.py` within the class `GithubWebhookListener`.

Additionally, we need to look up the user to see if they are a collaborator on the repo itself. https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

github3 library has a way to do this by way of a Repository object, https://github.com/sigmavirus24/github3.py/blob/master/github3/repos/repo.py#L961 but we don't have such an object yet. We'll have to create such an object from the details in the event.

**Comment by omgjlk** [comment]
Taking a stab at this.

**Comment by omgjlk** [comment]
Submitted this upstream https://review.openstack.org/#/c/419684/

**Comment by omgjlk** [comment]
Resolved by https://github.com/BonnyCI/hoist/pull/101

**Comment by omgjlk** [comment]
This is partially live, but may not be doing things correctly. We're not seeing a gate event start on status being set.

**Comment by omgjlk** [comment]
Now we're seeing this work. Closing.
