### ISSUE TITLE
Use github integration instead of manual web hook configuration

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#77]
We have a Github Integration ( https://github.com/integration/bonnyci ). We'd like to use this instead of manually configured web hooks.

The code in our install of zuul supports this, but we need to do a few things before it can go live:

- [ ] Add key and integration ID to secrets
- [ ] Remove existing web hook configuration in current watched repos and install integration instead

**Comment by omgjlk** [comment]
We're waiting until after demo on January 19 before making the change.

**Comment by omgjlk** [comment]
Related: https://github.com/BonnyCI/zuul/pull/25

**Comment by missaugustina** [comment]
I had moved this to blocked because I was under the impression progress on it was blocked by the change that was linked. Is that accurate?

**Comment by jamielennox** [comment]
Talking with Ivan Žužak <support@github.com> 

Email on 	24 Mar thinking that github upstream had solved it. Replied on 27 Mar to say that it's still not fixed.

**Comment by mlangbehn** [comment]
@jamielennox if this issue is no longer blocked, please drop a note in here.

**Comment by jamielennox** [comment]
Let's have a strategy and start merging people this week.

Github seems to have fixed everything we need.

**Comment by omgjlk** [comment]
Discussion happened on IRC and in response to https://github.com/BonnyCI/bonnyci.org/pull/61

Current plan is to merge https://github.com/BonnyCI/zuul/pull/39 and restart Zuul. After which we can try moving an existing repo (such as https://github.com/j2sol/giftwrap) over to the integration. We'll need to merge https://github.com/BonnyCI/hoist/pull/349 shortly after restarting once we know things are working.

Document (with screenshots) migrating the giftwrap repo over.

We'll need to update docs on using the integration instead of web hooks, which is covered by https://github.com/BonnyCI/projman/issues/122

Plan is to restart zuul today, and use today/tomorrow to work out any bugs, with the full cut over done by EOD day after tomorrow (relative to this comment).

**Comment by omgjlk** [comment]
Looks like all the items here have been completed.
