### ISSUE TITLE
Document the BonnyCI workflow

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#84]
Describe what happens when a pull request is opened and how it gets tested, approved, gated, merged. Crib from the upstream OpenStack zuul/gerrit developer docs.

**Comment by mlangbehn** [comment]
@j2sol, is this issue related to #19's section on contributing to BonnyCI, or is it for end user pull requests (i.e. to a repository that is using BonnyCI)?

**Comment by eggshell** [comment]
@mlangbehn based on @j2sol 's mention of some BonnyCI-specific functions (ex: gating), I'd assume this issue is shooting for the latter.

**Comment by omgjlk** [comment]
This is about consumers _of_ BonnyCI rather than contributors _to_ BonnyCI.

Something along the lines of http://docs.openstack.org/infra/manual/developers.html perhaps. A graphic like that at the top could be produced, and some of the wording from http://docs.openstack.org/infra/manual/developers.html#automated-testing could be useful as well. 

We want to highlight that we offer a check pipeline that functions like Travis or Jenkins or other offerings on Github that test the change individually, independent of any other proposed change, and also a gate pipeline, which is new functionality not familiar to GitHub users. The gate is where once approved, changes are tested as they would merge, with other approved changes, to ensure what gets merged is what gets tested, with re-testing happening should one or more pending change fail the tests.
