### ISSUE TITLE
Document why CI matters, and how BonnyCI differentiates from other offerings

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#85]
Include research info on effective CI for projects, and our features that do not exist elsewhere.

**Comment by missaugustina** [comment]
For MVP much of this might be unsubstantiated, but I'll at least write up our hypotheses and add some footnotes for clarification.

**Comment by mlangbehn** [comment]
@missaugustina, this documentation should be linked to from [here](https://github.com/BonnyCI/lore#introduction). If it's concise for the MVP, it may make sense to just write it in that section?

**Comment by missaugustina** [comment]
The decision was made to de-prioritize this since it was not deemed as crucial for MVP.

**Comment by missaugustina** [comment]
Issue #116 and this one are pretty much the same thing, or at least that's how it's turning out.
