### ISSUE TITLE
Document contributor on-boarding process

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#86]
We have a different audience, where people want to contribute to make BonnyCI (and the tools it uses) better. We need to document how people can join in the fun.

**Comment by omgjlk** [comment]
There should be clear distinction between contributor docs vs end user docs.

**Comment by missaugustina** [comment]
For MVP, the goal here should be contributor docs that the team needs in order to work effectively together. We can iterate on these docs as we get to a place where we want to start involving more external contributors.

**Comment by mlangbehn** [comment]
~Here is a link to the existing documentation for contributing: https://github.com/BonnyCI/lore/tree/master/contributing
Here is a link to the pull request I am working on to make the distinction between end user and developer docs more clear: https://github.com/BonnyCI/lore/tree/master/contributing~

**EDIT**
Documentation has been changed to help make the distinction more clear:
https://github.com/BonnyCI/lore

@j2sol, does this meet what you are looking for or are there other requirements?

**Comment by eggshell** [comment]
We've also added some documentation on [setting up a dev environment](https://github.com/BonnyCI/lore/tree/master/getting_started).

Also, the pull request @mlangbehn mentioned above is located [here](https://github.com/BonnyCI/lore/pull/18).

**Comment by mlangbehn** [comment]
Closing issue as lore has been updated accordingly.
