### ISSUE TITLE
Create a form letter and/or blog post for contacting potential beta testers

### ISSUE THREAD

**Issue by SpamapS** [BonnyCI/projman#89]
We will be contacting projects and should be consistent in our messaging. I'll create a blog post and/or form letter that we can send to mailing lists / forums / irc etc. to open up a conversation about being a beta tester without being too spammy.

**Comment by SpamapS** [comment]
FYI, the website is up, and looks terrible. http://bonnyci.org/about/ suffices as a medium-form version. I'll add a blog post with more later. So I'd say this is about half-done.

**Comment by missaugustina** [comment]
What else is left to do?

**Comment by SpamapS** [comment]
http://bonnyci.org/beta/ is the long form and should be a good place to send communities to evaluate whether or not they want to join up.
