### ISSUE TITLE
Nodepool high disk usage alerts

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#90]
We need alerts when the nodepool server's disk usage is getting full and is completely full. If we only alert when the disk is full it would be too late to prevent an outage, so we want preventative alerting here. I'm proposing 75% as a start, but we should look at the data from the past outage to see if that would have caught this.

This is one of the action items identified from Issue #88

**Comment by loafyloaf** [comment]
I don't think we can make datadog alert on a percentage of disk space, but absolute values aren't a problem.  What I've set up is a warning for 3GB of disk space left, and an alert for 1.5GB.  Currently, this will send to auggy, jlk and myself.

**Comment by jamielennox** [comment]
from: http://docs.datadoghq.com/integrations/disk/

system.disk.free
(gauge) 	The amount of disk space that is free.
shown as byte
system.disk.in_use
(gauge) 	The amount of disk space in use as a fraction of the total.
shown as fraction

so these as a fraction should be usable for an alert?
