### ISSUE TITLE
Root cause research: why didn't nodepool monitoring report an issue when the disk was full?

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#91]
Why did nodepool monitoring report that everything was fine when it wasn't?

Action item via Issue #88

**Comment by loafyloaf** [comment]
so... free disk space on nodepool was pretty constant over the last month.  but starting 1/9, the amount free disk space steadily and slowly diminished until the outage on 1/19. jlk's actions cleared up a bunch of space, but we are now on track to run out of space again by 1/29...
![nodepool_diskfree](https://cloud.githubusercontent.com/assets/2438948/22293305/139f612a-e2dd-11e6-91c7-0109d8f9ade3.png)

**Comment by loafyloaf** [comment]
root cause?  no alert had been set up.  this has been shown to be rectified.
