### ISSUE TITLE
Alert for zookeeper connectivity issues

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#92]
Action item resulting from Issue #88

**Comment by missaugustina** [comment]
What's the status of this? Do we have a monitor in place? If so please update this issue with that info! Thanks!

**Comment by loafyloaf** [comment]
the 'zookeeper went down' alert is specified in the datadog-monitors repo in the monitors.yml file.  currently, here: https://github.com/BonnyCI/datadog-monitors/blob/master/monitors.yml#L76 , but that line number is sure to change...
