### ISSUE TITLE
Audit current monitors

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#95]
Put together a spreadsheet listing out what monitors we currently have running.

https://ibm.box.com/s/astoyhjujvaa9xg4xii38j3q0f3fs4p6

**Comment by loafyloaf** [comment]
There are currently only 10 monitors in place - most of them look to have been set up by jamie

quick link (requires login): https://app.datadoghq.com/monitors#manage

**Comment by loafyloaf** [comment]
Status | Name | Definition | Tags	
-------- | ------- | ------------ | ------
OK |	[Auto] Clock in sync with NTP | ntp.in_sync | * 	
OK | free disk space on nodepool | system.disk.free | host:nodepool.bonnyci.portbleu.com 	
OK | Gearman is down on {{host.name}}	 | gearman.can_connect | * 	
Warn | Missing Mergers | gearman.workers_by_task | host:zuul task:merger:merge 	
No Data | Missing Mergers on playground | gearman.workers_by_task	task:merger:merge | host:contrasjc-bastion-2 	
OK | MySQL has gone down | mysql.can_connect | * 	
No Data | mysqld process from ansible | process.up | host:zuul process:mysql 	
No Data | mysqld process from ansible d | process.up | host:zuul process:mysql 	
OK | Zookeeper down! | zookeeper.ruok | * 	
OK | zuul merger count | gearman.workers_by_task | host:zuul task:merger:merge

**Comment by loafyloaf** [comment]
sorry - I wasn't having much luck editing that box spreadsheet (does it work with linux?), so I just put the info in the comments section

**Comment by missaugustina** [comment]
Reopening this -> per planning meeting conversation, we should create a doc with this info and add it to the datadog-monitoring repo.

**Comment by loafyloaf** [comment]
monitors.yml in the datadog-monitors repo pretty much serves as a living document as to what is being monitored.  it runs on a cron job to make sure monitors are established.  this will be continuously updated, so I think this issue is resolved - but feel free to reopen if the opposite is true
