### ISSUE TITLE
Add alert for stale nodepool DIB image builds / stalled builds

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#98]
If nodepool builder is failing to build images, the age of the images listed via 'nodepool dib-image-list' will grow beyond an expected threshold.  We should be able to check this with datadog via the nodepool webapp, in the same way we check nodepool status.  $nodepool_addr:8005/dib-image-list.json provides a json formatted list of available dib images with their age

**Comment by missaugustina** [comment]
FYI: The "monitoring alerts" label is for tickets filed in response to an alert

**Comment by loafyloaf** [comment]
so far, the associated PR creates a custom check.  a monitor will need to be added to monitors.yml in datadog-monitors to query this check.

**Comment by eggshell** [comment]
I've added the needed datadog monitor in BonnyCI/datadog-monitors#16

**Comment by mlangbehn** [comment]
@eggshell, should we mark this issue as done, now that BonnyCI/datadog-monitors#16 has merged?

**Comment by eggshell** [comment]
@mlangbehn  yes, I'll go ahead and close it.
